config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get 'private_article', to: :private_article, controller: 'articles'
  resources :articles do
    member do
      get 'like'
    end

    resources :texts do
      member do
        get 'like'
      end
    end

    resources :images do
      member do
        get 'like'
      end
    end
    
  end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  # before_save :chage_time_zone
  has_many :texts
  has_many :images
  scope :public_article, -> {where('date_up <= ?', Time.now)}
  scope :private_article, -> {where('date_up > ?', Time.now)}
  validates :title, :date_up, presence: true
  validates :like, numericality: { greater_than: -1 }

  private
    def chage_time_zone
      self.date_up.change(offset: Time.zone.now.strftime("%z"))
    end

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :article

  validates :headline, :image, :no, presence: true
  validates :like, numericality: { greater_than: -1 }
  mount_uploader :image, ImageUploader
end

app/models/text.rb
class Text < ApplicationRecord
  belongs_to :article
  validates :headline, :no, :content, presence: true
  validates :like, numericality: { greater_than: -1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def like_compoment(recode,url,msgs, msgf)
    recode.like = recode.like.to_i + 1
    return redirect_to article_path(url), notice: msgs if recode.save
    redirect_to articles_path,
    flash[:alert] = msgf
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_articles, only: [:show, :update, :destroy, :edit, :like]
  before_action :article_params, only: [:create, :update]

  def index
    @articles = Article.public_article.order('date_up desc')
  end

  def private_article
    @articles = Article.private_article
  end

  def show
    @attibutes = (@article.images + @article.texts).sort_by &:no
  end

  def edit
  end

  def update
    return redirect_to article_path(@article), notice: 'Create success!' if @article.update(@articles_params)
    redirect_to :new
    flash[:alert] = 'Create error'
  end

  def create
    @article = Article.new(@articles_params)
    return redirect_to new_article_image_path(@article), notice: 'Create success!' if @article.save
    render :new
    flash[:alert] = 'Create error'
  end

  def new
    @article = Article.new
  end

  def destroy
    return redirect_to articles_path, notice: 'Delete success!' if @article.destroy
    redirect_to articles_path,
    flash[:alert] = 'Delete error'
  end

  def like
    like_compoment(@article,@article, 'Like article success', 'Error not like')
  end

  private
    def article_params
      @articles_params = params.require(:article).permit(:title, :date_up, :like)
    end
    def get_articles
      @article = Article.find(params[:id])
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :get_image, only: [:update, :destroy, :edit, :like]
  before_action :image_params, only: [:create, :update]

  def edit
  end

  def update
    return redirect_to edit_article_path(@image.article), notice: 'Update success!' if @image.update(@images_params)
    redirect_to edit_article_image_path(@image.article, @image),
    flash[:alert] = 'Create error'
  end

  def create
    @image = Image.new(@images_params)
    
    return redirect_to new_article_text_path(@image.article), notice: 'Create success!' if @image.save
    render :new
    flash[:alert] = 'Create error'
  end

  def new
    @image = Image.new
  end

  def destroy
    return redirect_to edit_article_path(@image.article), notice: 'Delete success!' if @image.destroy
    redirect_to edit_article_path(@image.article_id),
    flash[:alert] = 'Delete error'
  end
  def like
    like_compoment(@image,@image.article, 'Like image success', 'Error not like')
  end
  private
    def image_params
        @images_params = params.require(:image).permit(:headline, :no, :image, :article_id, :like)
    end
    def get_image
      @image = Image.find(params[:id])
    end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :get_Texts, only: [:update, :destroy, :edit, :like]
  before_action :text_params, only: [:create, :update]

  def update
    return redirect_to edit_article_path(@text.article), notice: 'Update success!' if @text.update(@texts_params)
    redirect_to edit_article_text_path(:article_id => @text.article, id: @text),
    flash[:alert] = 'Create error'
  end

  def create
    @text = Text.new(@texts_params)
    return redirect_to article_path(@text.article_id), notice: 'Create success!' if @text.save
    render :new
    flash[:alert] = 'Create error'
  end

  def new
    @text = Text.new
  end

  def destroy
    return redirect_to edit_article_path(@text.article), notice: 'Delete success!' if @text.destroy
    redirect_to articles_path
    flash[:alert] = 'Delete error'
  end

  def like
    like_compoment(@text, @text.article,'Like text success!', 'Error not like')
  end
  private
    def text_params
      @texts_params = params.require(:text).permit(:headline, :no, :content, :article_id, :like)
    end
    def get_Texts
      @text = Text.find(params[:id])
    end
end

app/views/articles/_article.slim
p
  h4
    a.desc> href=article_path(article) = article.title
  p.desc
    =article.texts.first.try(:content)
  p
    a.btn.btn-info.like_like> href=like_article_path(article) Like article
    a.btn.btn-warning> href= edit_article_path(article) Edit
    =link_to('Delete article', article_path(article), class: 'btn btn-danger', method: :delete, data: {confirm: 'Art you sure'})
  - if article.like>0
    p.like_show
      |Like artile:
      = article.like

app/views/articles/_attibutes_image_text.slim
-if array.try(:image)
  p
    img src=array.image
  h5 =array.headline
  p.like
    - if array.like > 0
      |Like image:
      =array.like
    p.like
      a.btn.btn-info.like_like> href=like_article_image_path(array.article,array) Like Image
-else
  p
    p = array.content
  p.like
    - if array.like > 0
      |Like text:
      = array.like
    p.like
      a.btn.btn-info.like_like> href=like_article_text_path(array.article,array) Like Text

app/views/articles/edit.slim
h1 Edit Article
= semantic_form_for @article do |f|
  = f.input :title, :input_html => { :class => 'form-control'}
  = f.input :date_up, :input_html => { :class => 'form-control'}
  = f.actions :submit, :cancel

- @article.images.each do |image|
  p = image.headline
  a.btn.btn-warning> href=edit_article_image_path(@article, image) Edit
  =link_to('Delete Image', article_image_path(@article, image), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'})

- @article.texts.each do |text|
  p =text.headline
  a.btn.btn-warning> href=edit_article_text_path(@article, text) Edit
  =link_to('Delete Text',article_text_path(@article, text), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'})
p
  a> href=new_article_image_path(@article) Add Image
  a> href=new_article_text_path(@article) Add Text

app/views/articles/index.slim
a.btn.btn-success> href=new_article_path Add article
h2 List
= render partial: 'article', collection: @articles

app/views/articles/new.slim
h1 Create Article
= semantic_form_for @article do |f|
  = f.input :title, :input_html => { :class => 'form-control'}
  = f.input :date_up, :input_html => { :class => 'form-control', id: 'time'}
  = f.actions :submit, :cancel

app/views/articles/private_article.slim
a> href= new_article_path Add Text
h2 List
= render partial: 'article', collection: @articles

app/views/articles/show.slim
h1 Text
p
  - if @article.like > 0
    |Like:
    =@article.like
  p
    a.btn.btn-info> href=like_article_path(@article) Like article
h4
  = @article.title
span
  |created:
  = @article.date_up
- @attibutes.each do |array|
  = render 'attibutes_image_text', array: array

/ = render partial: 'texts/text', collection: @article.texts

app/views/images/_image.slim
-if array.try(:image)
  p
    p = array.headline
    p = array.like
    img src=array.image
  p.like
    |Like:
    =array.like
    p.like
      a> href=like_article_image_path(array.article,array) Like Image
-else
  p
    p = array.headline
    p = array.like
    p = array.content
  p.like
    |Like:
    =array.like
    p.like
      a> href=like_article_text_path(array.article,array) Like Text

app/views/images/edit.slim
h1 Create Image
= semantic_form_for @image , url: article_image_path(params[:article_id], @image), :multipart => true do |f|
  = f.input :headline, :input_html => { :class => 'form-control'}
  = f.input :no, :input_html => { :class => 'form-control'}
  = f.input :image, :input_html => { :class => 'form-control'}
  = f.input :article, :as => 'hidden', :input_html => {value: params[:article_id], :class => 'form-control'}
  = f.actions :submit, :cancel

app/views/images/new.slim
h1 Create Image
= semantic_form_for @image , url: article_images_path(params[:article_id]), :multipart => true do |f|
  = f.input :headline, :input_html => { :class => 'form-control'}
  = f.input :no, :input_html => { :class => 'form-control'}
  = f.input :image, :input_html => { :class => 'form-control'}
  = f.input :article, as: 'hidden', :input_html => {name: 'image[article_id]',value: params[:article_id], :class => 'form-control'}
  = f.actions :submit
a> href= new_article_text_path(params[:article_id]) Next add Text

app/views/layouts/application.slim
doctype html
html
  head
    title Articles
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    div.container
      a.btn.btn-primary.active> href= articles_path Home
      = yield

app/views/texts/edit.slim
h1 Create Text
= semantic_form_for @text, url: article_text_path(params[:article_id], @text) do |f|
  = f.input :headline, :input_html => { :class => 'form-control'}
  = f.input :no, :input_html => { :class => 'form-control'}
  = f.input :content, :input_html => { :class => 'form-control'}
  = f.input :article,:as => 'hidden', :input_html => {value: params[:article_id], :class => 'form-control'}
  = f.actions :submit, :cancel

app/views/texts/new.slim
h1 Create Text
= semantic_form_for @text, url: article_texts_path(params[:article_id]) do |f|
  = f.input :headline, :input_html => { :class => 'form-control'}
  = f.input :no, :input_html => { :class => 'form-control'}
  = f.input :content, :input_html => { :class => 'form-control'}
  = f.input :article,:as => 'hidden', :input_html => {name: 'text[article_id]',value: params[:article_id], :class => 'form-control'}
  = f.actions :submit